# Generated by Django 5.1.3 on 2026-05-27 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='deleted_at',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
