# Generated by Django 5.1.3 on 2026-05-28 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_alter_product_options_product_featured_user_is_pro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
