# Generated by Django 5.1.3 on 2026-05-28 16:16

import django.db.models.deletion
import ventas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pro_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProPaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=ventas.models.product_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_proofs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pro_payment_proofs',
                'ordering': ['-created_at'],
            },
        ),
    ]
