# Generated by Django 5.1.3 on 2026-05-28 21:17

import ventas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_user_pro_pending_propaymentproof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propaymentproof',
            name='image',
            field=models.ImageField(upload_to=ventas.models.proof_image_path),
        ),
    ]
