# Generated by Django 5.1.3 on 2026-05-31 05:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_fix_proof_upload_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('producto_falso', 'Producto Falso'), ('estafa', 'Estafa / Fraude'), ('robo', 'Robo de contenido / fotos'), ('acoso', 'Acoso / Maltrato'), ('spam', 'Spam / Publicidad no deseada'), ('precio_abusivo', 'Precio abusivo o engañoso'), ('suplantacion', 'Suplantación de identidad'), ('inapropiado', 'Contenido inapropiado'), ('otro', 'Otro')], max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('reviewed', 'Revisado'), ('dismissed', 'Desestimado'), ('action_taken', 'Medidas tomadas')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.order')),
                ('related_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.product')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Denuncia',
                'verbose_name_plural': 'Denuncias',
                'db_table': 'user_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
