# Generated by Django 5.1.3 on 2026-05-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_add_user_report_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='needs_onboarding',
            field=models.BooleanField(default=False),
        ),
    ]
