# Generated by Django 5.2.15 on 2026-06-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0015_add_needs_onboarding_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
